### PR TITLE
Support rubies 2.0->2.7 in win gem cross-compile

### LINKED ISSUE #1: Support Ruby 2.4, 2.5 and 2.6 on Windows
Please, add support Ruby 2.4, 2.5 and 2.6 on Windows.

### PR DESCRIPTION
**Pull request by marcparadise**
This updates the rakefile and dependencies to support
cross-compiling windows gems from 2.0 -> 2.7. This corrects a problem
in current windows installation of this gem, where ruby version > 2.3
will fail to load the extension library.

Fixes #1 

In order to build without errors, I needed to remove temp artifacts (`rake clean`; rm -rf vendor; rm -rf pkg) and make sure I was using ruby 2.7. 

I was able to verify that the built bcrypt_pbkdf-1.0.1-x64-mingw32.gem installed and loaded teh extension correctly under Windows 10.latest, with Ruby 2.6 installed.  I have not verified it with other ruby versions, though I'd expect it to work fine since the version-specific extension libraries are correctly built and placed.

Signed-off-by: Marc A. Paradise <marc.paradise@gmail.com>

### CODE REVIEW

**Comment by marcparadise** [comment]
I did not version bump, but can include it in this PR if it's the right place.

**Review by mfazekas — APPROVED** [review]

**Comment by marcparadise** [comment]
I can roll back the lockfile change, but then it will fail on 2.7. 

I wonder if it would be best to omit the lockfile from the repository?

**Comment by mfazekas** [comment]
> I can roll back the lockfile change, but then it will fail on 2.7.
> 
> I wonder if it would be best to omit the lockfile from the repository?

Yep i was wondered on the same, i guess we should not have the lockfile checked in

**Comment by marcparadise** [comment]
Looks like the updated dependencies limit ruby versions, with the lowest we can use being 2.3.0. 

Would it be okay to drop the older/unsupported ruby versions, maybe with a major gem version bump?

**Comment by mfazekas** [comment]
@marcparadise i think the issue is that old rubygem tries to upgrade to a version that is not supported on the ruby engine. I guess we can remove old ruby-s from CI, but i'd still buid for those unless there will be build errrors too.

**Comment by marcparadise** [comment]
Okay, I'll update travis. When I ran the build of what's in this PR, I did get the full range of versions: 
capture_076

**Comment by marcparadise** [comment]
That gets us there.  I also had to remove rubinius from travis - even though the travis docs say it's supported, it's not available.  Tried rbx-2 and rbx-3.

**Comment by mfazekas** [comment]
@marcparadise FIY the official repo is `https://github.com/net-ssh/bcrypt_pbkdf-ruby/` i'll push this change there too

**Comment by mfazekas** [comment]
@marcparadise i've released 1.1.0.rc1 versions. Please test and send feedback so i can release final versions

👍

**Comment by marcparadise** [comment]
Thanks @mfazekas , looking at that right now

**Comment by marcparadise** [comment]
I've confirmed windows extension loads correctly for Ruby 2.4 -> 2.7. 

I was not able to get older rubies to install gems; however I was able to verify that each of the shipped ext libs have dependencies on the expected win-ruby runtimes. 

However, the windows gem now includes ext libs for 2.3 through 2.7, though we specified 2.0 through 2.7.  I did not dig deeply to see why that is and assume it's due to desupported rubies --  when verifying this, changing RUBY_CC_VERSION confirmed it was respecting the versions I gave it; it just wasn't building any of the older ones. 

Given that [net-ssh](https://github.com/net-ssh/net-ssh/blob/master/net-ssh.gemspec#L18) sets the minimum version limit to 2.3, that should make this safe for that use case - but I'm not familiar enough with usage outside of `net-ssh` to know if it could cause problems elsewhere. 

Would it be better to make it a major version bump to signal dropped platforms?

**Pull request merged**
